import { Inter } from "next/font/google";
import "./globals.css";
import MyLayout from "@/components/MyLayout";
import { MarketDataProvider } from "@/context/MarketDataContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cryptonite",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MarketDataProvider>
          <MyLayout>{children}</MyLayout>
        </MarketDataProvider>
      </body>
    </html>
  );
}
